import { DocumentChunk } from '../../types';
import { getOpenAIClient } from '../preprocessing/vectorizer';
import { OPENAI_MODELS, GENERATION_CONFIG } from '../../constants';

/**
 * Takes a question and the most relevant document chunks, then asks an AI model
 * to generate a complete answer based on that context. The AI is instructed to
 * only use information from the provided context and to cite sources.
 *
 * @param question - The user's question
 * @param relevantChunks - The document chunks that are most relevant to the question
 * @returns A complete answer generated by the AI model
 */
export async function generateAnswer(
  question: string,
  relevantChunks: DocumentChunk[]
): Promise<string> {
  const openai = getOpenAIClient();

  const context = relevantChunks
    .map((chunk, index) => {
      return `[Source: ${chunk.source}, Chunk ${chunk.chunkIndex}]\n${chunk.content}`;
    })
    .join('\n\n---\n\n');

  const systemPrompt = `You are a helpful assistant that answers questions based on the provided context from research papers. 
Your answers should be:
1. Accurate and based only on the provided context
2. Well-formulated and clear
3. Include specific details from the sources when relevant
4. If the context doesn't contain enough information to answer the question, say so clearly

Always cite the source when referencing specific information.`;

  const userPrompt = `Context from research papers:
${context}

Question: ${question}

Please provide a comprehensive answer based on the context above. Include source citations when referencing specific information.`;

  try {
    const response = await openai.chat.completions.create({
      model: OPENAI_MODELS.CHAT,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: GENERATION_CONFIG.TEMPERATURE,
      max_tokens: GENERATION_CONFIG.MAX_TOKENS,
    });

    const answer = response.choices[0]?.message?.content;
    if (!answer) {
      throw new Error('No answer generated from OpenAI');
    }

    return answer;
  } catch (error) {
    throw new Error(
      `Failed to generate answer: ${
        error instanceof Error ? error.message : 'Unknown error'
      }`
    );
  }
}
